# Generated by Django 3.2.5 on 2021-09-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='listings')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
